name: hive_preferences
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  hive: 1.4.1+1
  hive_flutter: 0.3.0+2
  get_it: 4.0.2
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
